apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: citizendiop/jhipsterbank
      context: ../jhipsterbank
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
