apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: default
type: Opaque
data:
  secret: WVdRMlltUTFOalprTXpoaFpERmxZamRpTm1SbFkyUmpOMkZsWTJZMU16UXhOR0V6T0dRd01URTFNMkV3TUdSaE5qTTFaVFZtTW1WaFptVTVOR1JpWmpOaU56QXhNbVExT0dOaU5ERTFNRFpoT1RRd1lXTXdOamsxWmpnMVpXVXdZak0wTURBMk5UWTFNamd4T0RobE5XSTRObVV4WkRKak1URmhZMlJsTmpFPQ==
